### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Martin36** [Sandsten/DT2140_HapticProject#1]
- [x] Be able to move the curling stone

- [x] Set gravity force to the Falcon when lifting the stone

- [x] Give the curling stone a force forward on release
